services:
  web:
    build: ./client
    depends_on: 
      - server
    ports: 
      - "5173:5173"
    volumes:
      - ./client:/app/client
      - node_modules:/app/client/node_modules

  server:
    build: ./server
    depends_on: 
      - db
    ports: 
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      NODE_ENV: production
      ENGINE_ENV: production
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: accessshield
      DB_PASSWORD: Z$r$tr$st
      DB_PORT: 5432
      FIREBASE_ACCESS_KEY: AKIA2UC27DGI67SIQYNL
      FIREBASE_SECRET_KEY: 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
      FIREBASE_STORAGE_BUCKET: access-shield-jagah.appspot.com
      SECRET_KEY: jagah
      ADMIN_PASSWORD: Z$r$tr$st 
      ENCRYPTION_KEY: Z$r$tr$st
    volumes:
      - ./server:/app/server
    deploy:
      resources:
        limits:
          cpus: "1.0"           
          memory: "2G"           
        reservations:
          cpus: "0.5"           
          memory: "1G" 

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Z$r$tr$st
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: rootpassword
    volumes:
      - ./minio_data:/data
      - ./minio_config:/root/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    restart: always

volumes:
  postgres_data:
  node_modules:

